variables:
  GIT_SUBMODULE_STRATEGY : recursive
  ARTIFACTS_PATH: /home/shelldocker_share

.build-image:
  tags:
    - docker-build
  before_script:
    - mkdir -p ${ARTIFACTS_PATH}/${CI_PIPELINE_ID}
  script:
    - cd ${ROOT_PATH}${IMAGE_NAME}/${IMAGE_TAG}
    - echo "Using docker build args '${DOCKER_BUILD_ARGS}'"
    - docker ${DOCKER_BUILD_CMD} ${DOCKER_BUILD_ARGS} --no-cache -t embeddedlinux/${IMAGE_NAME}:${IMAGE_TAG} .
    - cd -
    - docker save -o ${ARTIFACTS_PATH}/${CI_PIPELINE_ID}/${IMAGE_NAME}-${IMAGE_TAG} embeddedlinux/${IMAGE_NAME}:${IMAGE_TAG}

.build-image-x64:
  extends: .build-image
  variables:
    DOCKER_BUILD_CMD: "build"

stages:
  - build-node
  - deploy
  - cleanup

include:
  - "/.gitlab/ci/cleanup.yml"
  - "/.gitlab/ci/deploy.yml"
  - "/.gitlab/ci/node.yml"
